triggers:
- envs: []
  last_enabled_at: 2024-02-04 19:41:25.586649
  name: daily_update_at_5
  pipeline_uuid: green_taxi_etl
  schedule_interval: 0 5 * * *
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-04 19:36:00
  status: active
  variables: {}
